Port changes
3angleTech/nestJsApi pull request #3
Opened 2023-08-16 11:30 UTC by SchnWalter

2023-08-16 13:14 UTC, mcristi requested changes

2023-08-16 13:14 UTC, mcristi commented on src/common/email/email.module.ts
> +export class EmailModule {}
let's pluralize this module and its services

2023-08-16 13:14 UTC, mcristi commented on src/common/users/services/users.interface.ts
> +  create(createUserDto: CreateUserDto): Promise<User | null>;
This method should return only `User` objects, never null.

2023-08-16 13:14 UTC, mcristi commented on src/common/users/services/users.service.ts
>    findById(id: string): Promise<User | null> {
we should use `findOneOrFail` here

2023-08-16 13:14 UTC, mcristi commented on src/common/users/services/users.service.ts
> +    return await this.findById(userId) as User;
if in `findById` is used `findOneOrFail`, `as User` could be removed

2023-08-16 13:14 UTC, mcristi commented on src/config/security.config.ts
> +}
If we have an interface now, please update all the usages of the security configurations to use the interface.

2023-08-16 13:14 UTC, mcristi commented on src/common/users/services/users.service.ts
> +      this.logger.warn('SERVER_ERROR.USER.USERNAME_ALREADY_EXISTS');
why not a file const if it used in multiple places? a const will ease the refactoring

2023-08-16 13:14 UTC, mcristi commented on src/modules/accounts/services/accounts.service.ts
> +      throw new BadRequestException('SERVER_ERROR.USER.PASSWORDS_DO_NOT_MATCH');
same, I would prefere to have the keys kept in file constants

2023-08-16 13:14 UTC, mcristi commented on src/modules/accounts/services/accounts.service.ts
> +      throw new UnauthorizedException();
This check is not needed if `findById` will fail anyway at `findOneOrFail`

2023-08-16 13:14 UTC, mcristi commented on src/modules/accounts/services/accounts.service.ts
> +    if (user && user.active) {
let's rename `active` to `isActive` ... it's easier to read in a natural way.

2023-08-16 13:14 UTC, mcristi commented on src/modules/users/index.ts
>  export * from './users.module';
being a common module, it will be used by many others, so let's keep `'./services/users.interface` exported

2023-09-05 15:28 UTC, SchnWalter commented on src/modules/users/index.ts
>  export * from './users.module';
This module only contains the API endpoints controller, I've moved that code into `~common/users`.

2023-09-06 11:47 UTC, mcristi requested changes

2023-09-06 11:47 UTC, mcristi commented on .eslintrc.js
> +    "jsdoc/newline-after-description": "off",
Isn't this a rule in the lint?

2023-09-06 11:47 UTC, mcristi commented on src/common/users/services/users.interface.ts
> +  findByIdOrFail(id: string): Promise<User>;
`findById` should have `findByIdOrFail` behaviour by default. We should not have `orFail` methods exposed by services. If we expect to fail, we should catch the error, but it's not the case anywhere. 
Let's keep only `findById` with fail behaviour

2023-09-06 11:47 UTC, mcristi commented on src/modules/accounts/services/accounts.service.ts
> +      throw new BadRequestException('SERVER_ERROR.USER.PASSWORDS_DO_NOT_MATCH');
still not resolved

2023-09-06 12:26 UTC, mcristi approved these changes

2023-09-06 12:28 UTC, merged